module.exports = function(grunt) {

    var host = 'localhost';
    var port = 7979;

    var dataDir = 'app/data';
    var jsonOutputPath = dataDir+'/entries.json';

    var lessVariablesPath = "app/less/variables.less";
    // Project configuration.
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        //JSHint detects errors and potential problems in JavaScript code
        jshint: {
            all: [ 'Gruntfile.js', 'app/*.js', 'app/**/*.js','app/**/*.json','!app/src/iliasjs/**/*.js' ]
        },
        less_imports: {
            default: {
                options: {
                    banner: "// This file was generated by grunt-less-imports and grunt-contrib-less, please do not change it, change according less files instead",
                    import: 'once'
            },
                files: [{
                    "app.less": [
                        "app/less/bootstrap-import.less",
                        "app/less/variables.less",
                        "app/data/**/*.variables.less",
                        "app/data/**/*.less",
                        "app/less/mixins/*.less",
                        "app/less/font.less",
                        "app/less/app/**/*.less",
                        "app/less/modules/**/*.less",
                        "app/less/services/**/*.less"]
                }]
            }
        },
        less: {
            default: {
                options: {
                    banner: "// This file was generated by grunt-less-imports and grunt-contrib-less, please do not change it, change according less files instead",
                    paths: ["."],
                    sourceMap: true,
                    outputSourceFiles: true,
                    sourceMapRootpath: "../../../",
                    sourceMapURL: "app.css.map"
                },
                files: {
                    "app/static/css/app.css": "app.less"
                }
            }
        },
        //Starts server at 8080
        connect: {
            server: {
                options: {
                    hostname: host,
                    port: port
                }
            }
        },
        // Automatically inject Bower components into the app
        wiredep: {
            default: {
                exclude: [ 'libs/bootstrap/dist/css/bootstrap.css','libs/jstree/dist/themes/default/style.css' ],
                src: [
                    'index.html'
                ]
            }
        },
        // Automatically inject custom components
        includeSource: {
            options: {
                basePath: 'app',
                baseUrl: '/app/'

            },
            target: {
                files: {
                    'index.html': 'app/index.html'
                }
            }
        },
        //Automatically detect file changes and take according actions
        watch: {
            default: {
                files: [ 'Gruntfile.js','app/less/**/*.less','app/less/services/**/**/*.less', 'app/data/**/*.*','app/**/*.js','tasks/*.js', 'app/**/*.html',dataDir+'/**/*.json','!'+jsonOutputPath],
                tasks: [ 'jshint','less_imports','less','includeSource', 'wiredep','buildEntriesJson','addLessVariablesFromFile','addLessRelationsFromEntries','startServerInfo'],
                options: {
                    atBegin: true,
                    debounceDelay: 550
                }
            }

        },
        //Builds the json data structure for the entries
        buildEntriesJson: {
            default: {
                dataDir: dataDir,
                htmlTemplatePath: dataDir+'/entry.template.html',
                jsonTemplatePath: dataDir+'/entry.template.json',
                jsonOutputPath: jsonOutputPath
            }
        },
        //Reads entries from variables.less file
        addLessVariablesFromFile: {
            default: {
                dataDir: dataDir,
                lessVariablesPath: lessVariablesPath,
                jsonOutputPath: jsonOutputPath,
                jsonVariablesIndex:{
                    first: 0,
                    second: 2
                }

            }
        },
        //Reads entries from variables.less file
        addLessRelationsFromEntries: {
            default: {
                dataDir: dataDir,
                jsonOutputPath: jsonOutputPath
            }
        },
        //Display Info about server state
        startServerInfo: {
            default: {
                state:"started",
                host: host,
                port: port
            }
        }

    });

    grunt.loadNpmTasks('grunt-wiredep');
    grunt.loadNpmTasks('grunt-include-source');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-connect');
    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-contrib-less');
    grunt.loadNpmTasks('grunt-less-imports');

    grunt.task.loadTasks("tasks/");


    grunt.registerTask('default', ['connect:server','watch']);
    grunt.registerTask('buildEntries', ['buildEntriesJson','addLessVariablesFromFile','addLessRelationsFromEntries']);
    grunt.registerTask('test', ['addLessVariablesFromFile']);

};